(define (problem task)
(:domain robot_delivery)
(:objects
wp0 wp1 wp2 wp3 wp4 wp5 - waypoint
machine0 machine1 machine2 machine3 machine4 - machine
robot0 robot1 robot2 - robot
)
(:init
    (robot_at robot0 wp0)
    (nocarrying_order robot0)
    (undocked robot0)
    (localised robot0)

    (robot_at robot1 wp0)
    (nocarrying_order robot1)
    (undocked robot1)
    (localised robot1)

    (robot_at robot2 wp0)
    (nocarrying_order robot2)
    (undocked robot2)
    (localised robot2)

    (machine_off machine0)
    (machine_off machine1)
    (machine_off machine2)
    (machine_off machine3)
    (machine_off machine4)

    (delivery_destination wp2) (at 217 (not (delivery_destination wp2)))
    (delivery_destination wp3) (at 217 (not (delivery_destination wp3)))
    (delivery_destination wp4) (at 217 (not (delivery_destination wp4)))

    (= (distance wp0 wp1) 8)
    (= (distance wp1 wp0) 8)
    (= (distance wp0 wp2) 36)
    (= (distance wp2 wp0) 36)
    (= (distance wp0 wp3) 9)
    (= (distance wp3 wp0) 9)
    (= (distance wp0 wp4) 26)
    (= (distance wp4 wp0) 26)
    (= (distance wp0 wp5) 25)
    (= (distance wp5 wp0) 25)
    (= (distance wp1 wp2) 29)
    (= (distance wp2 wp1) 29)
    (= (distance wp1 wp3) 4)
    (= (distance wp3 wp1) 4)
    (= (distance wp1 wp4) 19)
    (= (distance wp4 wp1) 19)
    (= (distance wp1 wp5) 18)
    (= (distance wp5 wp1) 18)
    (= (distance wp2 wp3) 28)
    (= (distance wp3 wp2) 28)
    (= (distance wp2 wp4) 11)
    (= (distance wp4 wp2) 11)
    (= (distance wp2 wp5) 12)
    (= (distance wp5 wp2) 12)
    (= (distance wp3 wp4) 18)
    (= (distance wp4 wp3) 18)
    (= (distance wp3 wp5) 17)
    (= (distance wp5 wp3) 17)
    (= (distance wp4 wp5) 16)
    (= (distance wp5 wp4) 16)
    (= (distance wp0 machine0) 34)
    (= (distance machine0 wp0) 34)
    (= (distance wp0 machine1) 20)
    (= (distance machine1 wp0) 20)
    (= (distance wp0 machine2) 22)
    (= (distance machine2 wp0) 22)
    (= (distance wp0 machine3) 23)
    (= (distance machine3 wp0) 23)
    (= (distance wp0 machine4) 22)
    (= (distance machine4 wp0) 22)
    (= (distance wp1 machine0) 27)
    (= (distance machine0 wp1) 27)
    (= (distance wp1 machine1) 25)
    (= (distance machine1 wp1) 25)
    (= (distance wp1 machine2) 21)
    (= (distance machine2 wp1) 21)
    (= (distance wp1 machine3) 22)
    (= (distance machine3 wp1) 22)
    (= (distance wp1 machine4) 15)
    (= (distance machine4 wp1) 15)
    (= (distance wp2 machine0) 5)
    (= (distance machine0 wp2) 5)
    (= (distance wp2 machine1) 19)
    (= (distance machine1 wp2) 19)
    (= (distance wp2 machine2) 15)
    (= (distance machine2 wp2) 15)
    (= (distance wp2 machine3) 16)
    (= (distance machine3 wp2) 16)
    (= (distance wp2 machine4) 15)
    (= (distance machine4 wp2) 15)
    (= (distance wp3 machine0) 26)
    (= (distance machine0 wp3) 26)
    (= (distance wp3 machine1) 22)
    (= (distance machine1 wp3) 22)
    (= (distance wp3 machine2) 18)
    (= (distance machine2 wp3) 18)
    (= (distance wp3 machine3) 19)
    (= (distance machine3 wp3) 19)
    (= (distance wp3 machine4) 14)
    (= (distance machine4 wp3) 14)
    (= (distance wp4 machine0) 11)
    (= (distance machine0 wp4) 11)
    (= (distance wp4 machine1) 13)
    (= (distance machine1 wp4) 13)
    (= (distance wp4 machine2) 9)
    (= (distance machine2 wp4) 9)
    (= (distance wp4 machine3) 10)
    (= (distance machine3 wp4) 10)
    (= (distance wp4 machine4) 9)
    (= (distance machine4 wp4) 9)
    (= (distance wp5 machine0) 10)
    (= (distance machine0 wp5) 10)
    (= (distance wp5 machine1) 28)
    (= (distance machine1 wp5) 28)
    (= (distance wp5 machine2) 24)
    (= (distance machine2 wp5) 24)
    (= (distance wp5 machine3) 25)
    (= (distance machine3 wp5) 25)
    (= (distance wp5 machine4) 8)
    (= (distance machine4 wp5) 8)
    (= (distance machine0 machine1) 23)
    (= (distance machine1 machine0) 23)
    (= (distance machine0 machine2) 19)
    (= (distance machine2 machine0) 19)
    (= (distance machine0 machine3) 20)
    (= (distance machine3 machine0) 20)
    (= (distance machine0 machine4) 13)
    (= (distance machine4 machine0) 13)
    (= (distance machine1 machine2) 5)
    (= (distance machine2 machine1) 5)
    (= (distance machine1 machine3) 4)
    (= (distance machine3 machine1) 4)
    (= (distance machine1 machine4) 21)
    (= (distance machine4 machine1) 21)
    (= (distance machine2 machine3) 2)
    (= (distance machine3 machine2) 2)
    (= (distance machine2 machine4) 17)
    (= (distance machine4 machine2) 17)
    (= (distance machine3 machine4) 18)
    (= (distance machine4 machine3) 18)
)
(:goal (and
    (order_delivered wp2)
    (order_delivered wp3)
    (order_delivered wp4)
))
)
