(define (problem task)
(:domain robot_delivery)
(:objects
wp0 wp1 wp2 wp3 wp4 wp5 - waypoint
machine0 machine1 machine2 machine3 - machine
robot0 robot1 robot2 - robot
)
(:init
    (robot_at robot0 wp0)
    (nocarrying_order robot0)
    (undocked robot0)
    (localised robot0)

    (robot_at robot1 wp0)
    (nocarrying_order robot1)
    (undocked robot1)
    (localised robot1)

    (robot_at robot2 wp0)
    (nocarrying_order robot2)
    (undocked robot2)
    (localised robot2)

    (machine_off machine0)
    (machine_off machine1)
    (machine_off machine2)
    (machine_off machine3)

    (delivery_destination wp0) (at 258 (not (delivery_destination wp0)))
    (delivery_destination wp2) (at 258 (not (delivery_destination wp2)))
    (delivery_destination wp1) (at 258 (not (delivery_destination wp1)))

    (= (distance wp0 wp1) 27)
    (= (distance wp1 wp0) 27)
    (= (distance wp0 wp2) 15)
    (= (distance wp2 wp0) 15)
    (= (distance wp0 wp3) 10)
    (= (distance wp3 wp0) 10)
    (= (distance wp0 wp4) 8)
    (= (distance wp4 wp0) 8)
    (= (distance wp0 wp5) 8)
    (= (distance wp5 wp0) 8)
    (= (distance wp1 wp2) 17)
    (= (distance wp2 wp1) 17)
    (= (distance wp1 wp3) 18)
    (= (distance wp3 wp1) 18)
    (= (distance wp1 wp4) 20)
    (= (distance wp4 wp1) 20)
    (= (distance wp1 wp5) 20)
    (= (distance wp5 wp1) 20)
    (= (distance wp2 wp3) 16)
    (= (distance wp3 wp2) 16)
    (= (distance wp2 wp4) 12)
    (= (distance wp4 wp2) 12)
    (= (distance wp2 wp5) 8)
    (= (distance wp5 wp2) 8)
    (= (distance wp3 wp4) 5)
    (= (distance wp4 wp3) 5)
    (= (distance wp3 wp5) 9)
    (= (distance wp5 wp3) 9)
    (= (distance wp4 wp5) 5)
    (= (distance wp5 wp4) 5)
    (= (distance wp0 machine0) 4)
    (= (distance machine0 wp0) 4)
    (= (distance wp0 machine1) 5)
    (= (distance machine1 wp0) 5)
    (= (distance wp0 machine2) 10)
    (= (distance machine2 wp0) 10)
    (= (distance wp0 machine3) 7)
    (= (distance machine3 wp0) 7)
    (= (distance wp1 machine0) 26)
    (= (distance machine0 wp1) 26)
    (= (distance wp1 machine1) 27)
    (= (distance machine1 wp1) 27)
    (= (distance wp1 machine2) 18)
    (= (distance machine2 wp1) 18)
    (= (distance wp1 machine3) 23)
    (= (distance machine3 wp1) 23)
    (= (distance wp2 machine0) 18)
    (= (distance machine0 wp2) 18)
    (= (distance wp2 machine1) 11)
    (= (distance machine1 wp2) 11)
    (= (distance wp2 machine2) 8)
    (= (distance machine2 wp2) 8)
    (= (distance wp2 machine3) 21)
    (= (distance machine3 wp2) 21)
    (= (distance wp3 machine0) 9)
    (= (distance machine0 wp3) 9)
    (= (distance wp3 machine1) 10)
    (= (distance machine1 wp3) 10)
    (= (distance wp3 machine2) 9)
    (= (distance machine2 wp3) 9)
    (= (distance wp3 machine3) 6)
    (= (distance machine3 wp3) 6)
    (= (distance wp4 machine0) 7)
    (= (distance machine0 wp4) 7)
    (= (distance wp4 machine1) 8)
    (= (distance machine1 wp4) 8)
    (= (distance wp4 machine2) 5)
    (= (distance machine2 wp4) 5)
    (= (distance wp4 machine3) 10)
    (= (distance machine3 wp4) 10)
    (= (distance wp5 machine0) 11)
    (= (distance machine0 wp5) 11)
    (= (distance wp5 machine1) 8)
    (= (distance machine1 wp5) 8)
    (= (distance wp5 machine2) 3)
    (= (distance machine2 wp5) 3)
    (= (distance wp5 machine3) 14)
    (= (distance machine3 wp5) 14)
    (= (distance machine0 machine1) 8)
    (= (distance machine1 machine0) 8)
    (= (distance machine0 machine2) 11)
    (= (distance machine2 machine0) 11)
    (= (distance machine0 machine3) 4)
    (= (distance machine3 machine0) 4)
    (= (distance machine1 machine2) 10)
    (= (distance machine2 machine1) 10)
    (= (distance machine1 machine3) 11)
    (= (distance machine3 machine1) 11)
    (= (distance machine2 machine3) 14)
    (= (distance machine3 machine2) 14)
)
(:goal (and
    (order_delivered wp0)
    (order_delivered wp2)
    (order_delivered wp1)
))
)
