(define (problem task)
(:domain robot_delivery)
(:objects
wp0 wp1 wp2 wp3 wp4 wp5 wp6 - waypoint
machine0 machine1 machine2 - machine
robot0 robot1 robot2 - robot
)
(:init
    (robot_at robot0 wp0)
    (nocarrying_order robot0)
    (undocked robot0)
    (localised robot0)

    (robot_at robot1 wp0)
    (nocarrying_order robot1)
    (undocked robot1)
    (localised robot1)

    (robot_at robot2 wp0)
    (nocarrying_order robot2)
    (undocked robot2)
    (localised robot2)

    (machine_off machine0)
    (machine_off machine1)
    (machine_off machine2)

    (delivery_destination wp4)
    (delivery_destination wp6)

    (= (distance wp0 wp1) 8)
    (= (distance wp1 wp0) 8)
    (= (distance wp0 wp2) 7)
    (= (distance wp2 wp0) 7)
    (= (distance wp0 wp3) 7)
    (= (distance wp3 wp0) 7)
    (= (distance wp0 wp4) 6)
    (= (distance wp4 wp0) 6)
    (= (distance wp0 wp5) 19)
    (= (distance wp5 wp0) 19)
    (= (distance wp0 wp6) 15)
    (= (distance wp6 wp0) 15)
    (= (distance wp1 wp2) 8)
    (= (distance wp2 wp1) 8)
    (= (distance wp1 wp3) 10)
    (= (distance wp3 wp1) 10)
    (= (distance wp1 wp4) 7)
    (= (distance wp4 wp1) 7)
    (= (distance wp1 wp5) 12)
    (= (distance wp5 wp1) 12)
    (= (distance wp1 wp6) 16)
    (= (distance wp6 wp1) 16)
    (= (distance wp2 wp3) 9)
    (= (distance wp3 wp2) 9)
    (= (distance wp2 wp4) 6)
    (= (distance wp4 wp2) 6)
    (= (distance wp2 wp5) 13)
    (= (distance wp5 wp2) 13)
    (= (distance wp2 wp6) 9)
    (= (distance wp6 wp2) 9)
    (= (distance wp3 wp4) 4)
    (= (distance wp4 wp3) 4)
    (= (distance wp3 wp5) 21)
    (= (distance wp5 wp3) 21)
    (= (distance wp3 wp6) 15)
    (= (distance wp6 wp3) 15)
    (= (distance wp4 wp5) 18)
    (= (distance wp5 wp4) 18)
    (= (distance wp4 wp6) 12)
    (= (distance wp6 wp4) 12)
    (= (distance wp5 wp6) 7)
    (= (distance wp6 wp5) 7)
    (= (distance wp0 machine0) 16)
    (= (distance machine0 wp0) 16)
    (= (distance wp0 machine1) 4)
    (= (distance machine1 wp0) 4)
    (= (distance wp0 machine2) 10)
    (= (distance machine2 wp0) 10)
    (= (distance wp1 machine0) 9)
    (= (distance machine0 wp1) 9)
    (= (distance wp1 machine1) 11)
    (= (distance machine1 wp1) 11)
    (= (distance wp1 machine2) 3)
    (= (distance machine2 wp1) 3)
    (= (distance wp2 machine0) 14)
    (= (distance machine0 wp2) 14)
    (= (distance wp2 machine1) 10)
    (= (distance machine1 wp2) 10)
    (= (distance wp2 machine2) 6)
    (= (distance machine2 wp2) 6)
    (= (distance wp3 machine0) 18)
    (= (distance machine0 wp3) 18)
    (= (distance wp3 machine1) 6)
    (= (distance machine1 wp3) 6)
    (= (distance wp3 machine2) 12)
    (= (distance machine2 wp3) 12)
    (= (distance wp4 machine0) 15)
    (= (distance machine0 wp4) 15)
    (= (distance wp4 machine1) 5)
    (= (distance machine1 wp4) 5)
    (= (distance wp4 machine2) 9)
    (= (distance machine2 wp4) 9)
    (= (distance wp5 machine0) 16)
    (= (distance machine0 wp5) 16)
    (= (distance wp5 machine1) 22)
    (= (distance machine1 wp5) 22)
    (= (distance wp5 machine2) 10)
    (= (distance machine2 wp5) 10)
    (= (distance wp6 machine0) 22)
    (= (distance machine0 wp6) 22)
    (= (distance wp6 machine1) 16)
    (= (distance machine1 wp6) 16)
    (= (distance wp6 machine2) 14)
    (= (distance machine2 wp6) 14)
    (= (distance machine0 machine1) 19)
    (= (distance machine1 machine0) 19)
    (= (distance machine0 machine2) 9)
    (= (distance machine2 machine0) 9)
    (= (distance machine1 machine2) 13)
    (= (distance machine2 machine1) 13)
)
(:goal (and
    (order_delivered wp4)
    (order_delivered wp6)
))
)
