(define (problem task)
(:domain robot_delivery)
(:objects
wp0 wp1 wp2 wp3 - waypoint
machine0 machine1 machine2 machine3 - machine
robot0 robot1 robot2 - robot
)
(:init
    (robot_at robot0 wp0)
    (nocarrying_order robot0)
    (undocked robot0)
    (localised robot0)

    (robot_at robot1 wp0)
    (nocarrying_order robot1)
    (undocked robot1)
    (localised robot1)

    (robot_at robot2 wp0)
    (nocarrying_order robot2)
    (undocked robot2)
    (localised robot2)

    (machine_off machine0)
    (machine_off machine1)
    (machine_off machine2)
    (machine_off machine3)

    (delivery_destination wp1)
    (delivery_destination wp2)
    (delivery_destination wp0)

    (= (distance wp0 wp1) 3)
    (= (distance wp1 wp0) 3)
    (= (distance wp0 wp2) 23)
    (= (distance wp2 wp0) 23)
    (= (distance wp0 wp3) 12)
    (= (distance wp3 wp0) 12)
    (= (distance wp1 wp2) 25)
    (= (distance wp2 wp1) 25)
    (= (distance wp1 wp3) 14)
    (= (distance wp3 wp1) 14)
    (= (distance wp2 wp3) 12)
    (= (distance wp3 wp2) 12)
    (= (distance wp0 machine0) 22)
    (= (distance machine0 wp0) 22)
    (= (distance wp0 machine1) 19)
    (= (distance machine1 wp0) 19)
    (= (distance wp0 machine2) 20)
    (= (distance machine2 wp0) 20)
    (= (distance wp0 machine3) 20)
    (= (distance machine3 wp0) 20)
    (= (distance wp1 machine0) 24)
    (= (distance machine0 wp1) 24)
    (= (distance wp1 machine1) 21)
    (= (distance machine1 wp1) 21)
    (= (distance wp1 machine2) 22)
    (= (distance machine2 wp1) 22)
    (= (distance wp1 machine3) 22)
    (= (distance machine3 wp1) 22)
    (= (distance wp2 machine0) 8)
    (= (distance machine0 wp2) 8)
    (= (distance wp2 machine1) 15)
    (= (distance machine1 wp2) 15)
    (= (distance wp2 machine2) 4)
    (= (distance machine2 wp2) 4)
    (= (distance wp2 machine3) 14)
    (= (distance machine3 wp2) 14)
    (= (distance wp3 machine0) 11)
    (= (distance machine0 wp3) 11)
    (= (distance wp3 machine1) 24)
    (= (distance machine1 wp3) 24)
    (= (distance wp3 machine2) 11)
    (= (distance machine2 wp3) 11)
    (= (distance wp3 machine3) 23)
    (= (distance machine3 wp3) 23)
    (= (distance machine0 machine1) 22)
    (= (distance machine1 machine0) 22)
    (= (distance machine0 machine2) 9)
    (= (distance machine2 machine0) 9)
    (= (distance machine0 machine3) 21)
    (= (distance machine3 machine0) 21)
    (= (distance machine1 machine2) 14)
    (= (distance machine2 machine1) 14)
    (= (distance machine1 machine3) 2)
    (= (distance machine3 machine1) 2)
    (= (distance machine2 machine3) 13)
    (= (distance machine3 machine2) 13)
)
(:goal (and
    (order_delivered wp1)
    (order_delivered wp2)
    (order_delivered wp0)
))
)
