(define (problem task)
(:domain robot_delivery)
(:objects
wp0 wp1 wp2 wp3 - waypoint
machine0 machine1 machine2 machine3 - machine
robot0 robot1 robot2 - robot
)
(:init
    (robot_at robot0 wp0)
    (nocarrying_order robot0)
    (undocked robot0)
    (localised robot0)

    (robot_at robot1 wp0)
    (nocarrying_order robot1)
    (undocked robot1)
    (localised robot1)

    (robot_at robot2 wp0)
    (nocarrying_order robot2)
    (undocked robot2)
    (localised robot2)

    (machine_off machine0)
    (machine_off machine1)
    (machine_off machine2)
    (machine_off machine3)

    (delivery_destination wp3)
    (delivery_destination wp0)

    (= (distance wp0 wp1) 36)
    (= (distance wp1 wp0) 36)
    (= (distance wp0 wp2) 24)
    (= (distance wp2 wp0) 24)
    (= (distance wp0 wp3) 23)
    (= (distance wp3 wp0) 23)
    (= (distance wp1 wp2) 13)
    (= (distance wp2 wp1) 13)
    (= (distance wp1 wp3) 14)
    (= (distance wp3 wp1) 14)
    (= (distance wp2 wp3) 20)
    (= (distance wp3 wp2) 20)
    (= (distance wp0 machine0) 9)
    (= (distance machine0 wp0) 9)
    (= (distance wp0 machine1) 16)
    (= (distance machine1 wp0) 16)
    (= (distance wp0 machine2) 9)
    (= (distance machine2 wp0) 9)
    (= (distance wp0 machine3) 15)
    (= (distance machine3 wp0) 15)
    (= (distance wp1 machine0) 28)
    (= (distance machine0 wp1) 28)
    (= (distance wp1 machine1) 21)
    (= (distance machine1 wp1) 21)
    (= (distance wp1 machine2) 30)
    (= (distance machine2 wp1) 30)
    (= (distance wp1 machine3) 22)
    (= (distance machine3 wp1) 22)
    (= (distance wp2 machine0) 16)
    (= (distance machine0 wp2) 16)
    (= (distance wp2 machine1) 9)
    (= (distance machine1 wp2) 9)
    (= (distance wp2 machine2) 22)
    (= (distance machine2 wp2) 22)
    (= (distance wp2 machine3) 16)
    (= (distance machine3 wp2) 16)
    (= (distance wp3 machine0) 15)
    (= (distance machine0 wp3) 15)
    (= (distance wp3 machine1) 16)
    (= (distance machine1 wp3) 16)
    (= (distance wp3 machine2) 17)
    (= (distance machine2 wp3) 17)
    (= (distance wp3 machine3) 9)
    (= (distance machine3 wp3) 9)
    (= (distance machine0 machine1) 12)
    (= (distance machine1 machine0) 12)
    (= (distance machine0 machine2) 7)
    (= (distance machine2 machine0) 7)
    (= (distance machine0 machine3) 7)
    (= (distance machine3 machine0) 7)
    (= (distance machine1 machine2) 18)
    (= (distance machine2 machine1) 18)
    (= (distance machine1 machine3) 12)
    (= (distance machine3 machine1) 12)
    (= (distance machine2 machine3) 9)
    (= (distance machine3 machine2) 9)
)
(:goal (and
    (order_delivered wp3)
    (order_delivered wp0)
))
)
