(define (problem task)
(:domain robot_delivery)
(:objects
wp0 wp1 wp2 wp3 - waypoint
machine0 machine1 machine2 - machine
robot0 robot1 robot2 - robot
)
(:init
    (robot_at robot0 wp0)
    (nocarrying_order robot0)
    (undocked robot0)
    (localised robot0)

    (robot_at robot1 wp0)
    (nocarrying_order robot1)
    (undocked robot1)
    (localised robot1)

    (robot_at robot2 wp0)
    (nocarrying_order robot2)
    (undocked robot2)
    (localised robot2)

    (machine_off machine0)
    (machine_off machine1)
    (machine_off machine2)

    (delivery_destination wp0)
    (delivery_destination wp3)
    (delivery_destination wp1)

    (= (distance wp0 wp1) 25)
    (= (distance wp1 wp0) 25)
    (= (distance wp0 wp2) 22)
    (= (distance wp2 wp0) 22)
    (= (distance wp0 wp3) 15)
    (= (distance wp3 wp0) 15)
    (= (distance wp1 wp2) 18)
    (= (distance wp2 wp1) 18)
    (= (distance wp1 wp3) 11)
    (= (distance wp3 wp1) 11)
    (= (distance wp2 wp3) 14)
    (= (distance wp3 wp2) 14)
    (= (distance wp0 machine0) 8)
    (= (distance machine0 wp0) 8)
    (= (distance wp0 machine1) 13)
    (= (distance machine1 wp0) 13)
    (= (distance wp0 machine2) 15)
    (= (distance machine2 wp0) 15)
    (= (distance wp1 machine0) 26)
    (= (distance machine0 wp1) 26)
    (= (distance wp1 machine1) 17)
    (= (distance machine1 wp1) 17)
    (= (distance wp1 machine2) 15)
    (= (distance machine2 wp1) 15)
    (= (distance wp2 machine0) 15)
    (= (distance machine0 wp2) 15)
    (= (distance wp2 machine1) 10)
    (= (distance machine1 wp2) 10)
    (= (distance wp2 machine2) 28)
    (= (distance machine2 wp2) 28)
    (= (distance wp3 machine0) 16)
    (= (distance machine0 wp3) 16)
    (= (distance wp3 machine1) 7)
    (= (distance machine1 wp3) 7)
    (= (distance wp3 machine2) 15)
    (= (distance machine2 wp3) 15)
    (= (distance machine0 machine1) 10)
    (= (distance machine1 machine0) 10)
    (= (distance machine0 machine2) 16)
    (= (distance machine2 machine0) 16)
    (= (distance machine1 machine2) 19)
    (= (distance machine2 machine1) 19)
)
(:goal (and
    (order_delivered wp0)
    (order_delivered wp3)
    (order_delivered wp1)
))
)
