(define (problem task)
(:domain robot_delivery)
(:objects
wp0 wp1 wp2 wp3 wp4 wp5 - waypoint
machine0 machine1 machine2 machine3 machine4 - machine
robot0 robot1 robot2 - robot
)
(:init
    (robot_at robot0 wp0)
    (nocarrying_order robot0)
    (undocked robot0)
    (localised robot0)

    (robot_at robot1 wp0)
    (nocarrying_order robot1)
    (undocked robot1)
    (localised robot1)

    (robot_at robot2 wp0)
    (nocarrying_order robot2)
    (undocked robot2)
    (localised robot2)

    (machine_off machine0)
    (machine_off machine1)
    (machine_off machine2)
    (machine_off machine3)
    (machine_off machine4)

    (delivery_destination wp1)
    (delivery_destination wp2)

    (= (distance wp0 wp1) 18)
    (= (distance wp1 wp0) 18)
    (= (distance wp0 wp2) 9)
    (= (distance wp2 wp0) 9)
    (= (distance wp0 wp3) 18)
    (= (distance wp3 wp0) 18)
    (= (distance wp0 wp4) 15)
    (= (distance wp4 wp0) 15)
    (= (distance wp0 wp5) 16)
    (= (distance wp5 wp0) 16)
    (= (distance wp1 wp2) 16)
    (= (distance wp2 wp1) 16)
    (= (distance wp1 wp3) 7)
    (= (distance wp3 wp1) 7)
    (= (distance wp1 wp4) 8)
    (= (distance wp4 wp1) 8)
    (= (distance wp1 wp5) 15)
    (= (distance wp5 wp1) 15)
    (= (distance wp2 wp3) 22)
    (= (distance wp3 wp2) 22)
    (= (distance wp2 wp4) 23)
    (= (distance wp4 wp2) 23)
    (= (distance wp2 wp5) 12)
    (= (distance wp5 wp2) 12)
    (= (distance wp3 wp4) 8)
    (= (distance wp4 wp3) 8)
    (= (distance wp3 wp5) 21)
    (= (distance wp5 wp3) 21)
    (= (distance wp4 wp5) 22)
    (= (distance wp5 wp4) 22)
    (= (distance wp0 machine0) 11)
    (= (distance machine0 wp0) 11)
    (= (distance wp0 machine1) 19)
    (= (distance machine1 wp0) 19)
    (= (distance wp0 machine2) 19)
    (= (distance machine2 wp0) 19)
    (= (distance wp0 machine3) 11)
    (= (distance machine3 wp0) 11)
    (= (distance wp0 machine4) 29)
    (= (distance machine4 wp0) 29)
    (= (distance wp1 machine0) 8)
    (= (distance machine0 wp1) 8)
    (= (distance wp1 machine1) 12)
    (= (distance machine1 wp1) 12)
    (= (distance wp1 machine2) 8)
    (= (distance machine2 wp1) 8)
    (= (distance wp1 machine3) 8)
    (= (distance machine3 wp1) 8)
    (= (distance wp1 machine4) 12)
    (= (distance machine4 wp1) 12)
    (= (distance wp2 machine0) 15)
    (= (distance machine0 wp2) 15)
    (= (distance wp2 machine1) 27)
    (= (distance machine1 wp2) 27)
    (= (distance wp2 machine2) 15)
    (= (distance machine2 wp2) 15)
    (= (distance wp2 machine3) 17)
    (= (distance machine3 wp2) 17)
    (= (distance wp2 machine4) 25)
    (= (distance machine4 wp2) 25)
    (= (distance wp3 machine0) 8)
    (= (distance machine0 wp3) 8)
    (= (distance wp3 machine1) 6)
    (= (distance machine1 wp3) 6)
    (= (distance wp3 machine2) 14)
    (= (distance machine2 wp3) 14)
    (= (distance wp3 machine3) 8)
    (= (distance machine3 wp3) 8)
    (= (distance wp3 machine4) 14)
    (= (distance machine4 wp3) 14)
    (= (distance wp4 machine0) 9)
    (= (distance machine0 wp4) 9)
    (= (distance wp4 machine1) 5)
    (= (distance machine1 wp4) 5)
    (= (distance wp4 machine2) 15)
    (= (distance machine2 wp4) 15)
    (= (distance wp4 machine3) 7)
    (= (distance machine3 wp4) 7)
    (= (distance wp4 machine4) 19)
    (= (distance machine4 wp4) 19)
    (= (distance wp5 machine0) 14)
    (= (distance machine0 wp5) 14)
    (= (distance wp5 machine1) 26)
    (= (distance machine1 wp5) 26)
    (= (distance wp5 machine2) 8)
    (= (distance machine2 wp5) 8)
    (= (distance wp5 machine3) 16)
    (= (distance machine3 wp5) 16)
    (= (distance wp5 machine4) 14)
    (= (distance machine4 wp5) 14)
    (= (distance machine0 machine1) 13)
    (= (distance machine1 machine0) 13)
    (= (distance machine0 machine2) 9)
    (= (distance machine2 machine0) 9)
    (= (distance machine0 machine3) 3)
    (= (distance machine3 machine0) 3)
    (= (distance machine0 machine4) 19)
    (= (distance machine4 machine0) 19)
    (= (distance machine1 machine2) 19)
    (= (distance machine2 machine1) 19)
    (= (distance machine1 machine3) 11)
    (= (distance machine3 machine1) 11)
    (= (distance machine1 machine4) 19)
    (= (distance machine4 machine1) 19)
    (= (distance machine2 machine3) 9)
    (= (distance machine3 machine2) 9)
    (= (distance machine2 machine4) 11)
    (= (distance machine4 machine2) 11)
    (= (distance machine3 machine4) 19)
    (= (distance machine4 machine3) 19)
)
(:goal (and
    (order_delivered wp1)
    (order_delivered wp2)
))
)
