(define (problem task)
(:domain robot_delivery)
(:objects
wp0 wp1 wp2 wp3 - waypoint
machine0 machine1 machine2 machine3 machine4 - machine
robot0 robot1 robot2 - robot
)
(:init
    (robot_at robot0 wp0)
    (nocarrying_order robot0)
    (undocked robot0)
    (localised robot0)

    (robot_at robot1 wp0)
    (nocarrying_order robot1)
    (undocked robot1)
    (localised robot1)

    (robot_at robot2 wp0)
    (nocarrying_order robot2)
    (undocked robot2)
    (localised robot2)

    (machine_off machine0)
    (machine_off machine1)
    (machine_off machine2)
    (machine_off machine3)
    (machine_off machine4)

    (delivery_destination wp0)
    (delivery_destination wp3)
    (delivery_destination wp1)

    (= (distance wp0 wp1) 24)
    (= (distance wp1 wp0) 24)
    (= (distance wp0 wp2) 3)
    (= (distance wp2 wp0) 3)
    (= (distance wp0 wp3) 4)
    (= (distance wp3 wp0) 4)
    (= (distance wp1 wp2) 26)
    (= (distance wp2 wp1) 26)
    (= (distance wp1 wp3) 23)
    (= (distance wp3 wp1) 23)
    (= (distance wp2 wp3) 4)
    (= (distance wp3 wp2) 4)
    (= (distance wp0 machine0) 17)
    (= (distance machine0 wp0) 17)
    (= (distance wp0 machine1) 15)
    (= (distance machine1 wp0) 15)
    (= (distance wp0 machine2) 2)
    (= (distance machine2 wp0) 2)
    (= (distance wp0 machine3) 11)
    (= (distance machine3 wp0) 11)
    (= (distance wp0 machine4) 23)
    (= (distance machine4 wp0) 23)
    (= (distance wp1 machine0) 8)
    (= (distance machine0 wp1) 8)
    (= (distance wp1 machine1) 24)
    (= (distance machine1 wp1) 24)
    (= (distance wp1 machine2) 23)
    (= (distance machine2 wp1) 23)
    (= (distance wp1 machine3) 14)
    (= (distance machine3 wp1) 14)
    (= (distance wp1 machine4) 4)
    (= (distance machine4 wp1) 4)
    (= (distance wp2 machine0) 19)
    (= (distance machine0 wp2) 19)
    (= (distance wp2 machine1) 17)
    (= (distance machine1 wp2) 17)
    (= (distance wp2 machine2) 4)
    (= (distance machine2 wp2) 4)
    (= (distance wp2 machine3) 13)
    (= (distance machine3 wp2) 13)
    (= (distance wp2 machine4) 25)
    (= (distance machine4 wp2) 25)
    (= (distance wp3 machine0) 16)
    (= (distance machine0 wp3) 16)
    (= (distance wp3 machine1) 18)
    (= (distance machine1 wp3) 18)
    (= (distance wp3 machine2) 5)
    (= (distance machine2 wp3) 5)
    (= (distance wp3 machine3) 10)
    (= (distance machine3 wp3) 10)
    (= (distance wp3 machine4) 22)
    (= (distance machine4 wp3) 22)
    (= (distance machine0 machine1) 17)
    (= (distance machine1 machine0) 17)
    (= (distance machine0 machine2) 16)
    (= (distance machine2 machine0) 16)
    (= (distance machine0 machine3) 7)
    (= (distance machine3 machine0) 7)
    (= (distance machine0 machine4) 9)
    (= (distance machine4 machine0) 9)
    (= (distance machine1 machine2) 14)
    (= (distance machine2 machine1) 14)
    (= (distance machine1 machine3) 23)
    (= (distance machine3 machine1) 23)
    (= (distance machine1 machine4) 23)
    (= (distance machine4 machine1) 23)
    (= (distance machine2 machine3) 10)
    (= (distance machine3 machine2) 10)
    (= (distance machine2 machine4) 22)
    (= (distance machine4 machine2) 22)
    (= (distance machine3 machine4) 15)
    (= (distance machine4 machine3) 15)
)
(:goal (and
    (order_delivered wp0)
    (order_delivered wp3)
    (order_delivered wp1)
))
)
