(define (problem task)
(:domain robot_delivery)
(:objects
wp0 wp1 wp2 wp3 wp4 - waypoint
machine0 machine1 machine2 - machine
robot0 robot1 robot2 - robot
)
(:init
    (robot_at robot0 wp0)
    (nocarrying_order robot0)
    (undocked robot0)
    (localised robot0)

    (robot_at robot1 wp0)
    (nocarrying_order robot1)
    (undocked robot1)
    (localised robot1)

    (robot_at robot2 wp0)
    (nocarrying_order robot2)
    (undocked robot2)
    (localised robot2)

    (machine_off machine0)
    (machine_off machine1)
    (machine_off machine2)

    (delivery_destination wp3)
    (delivery_destination wp0)
    (delivery_destination wp2)

    (= (distance wp0 wp1) 12)
    (= (distance wp1 wp0) 12)
    (= (distance wp0 wp2) 13)
    (= (distance wp2 wp0) 13)
    (= (distance wp0 wp3) 15)
    (= (distance wp3 wp0) 15)
    (= (distance wp0 wp4) 12)
    (= (distance wp4 wp0) 12)
    (= (distance wp1 wp2) 10)
    (= (distance wp2 wp1) 10)
    (= (distance wp1 wp3) 22)
    (= (distance wp3 wp1) 22)
    (= (distance wp1 wp4) 11)
    (= (distance wp4 wp1) 11)
    (= (distance wp2 wp3) 27)
    (= (distance wp3 wp2) 27)
    (= (distance wp2 wp4) 2)
    (= (distance wp4 wp2) 2)
    (= (distance wp3 wp4) 26)
    (= (distance wp4 wp3) 26)
    (= (distance wp0 machine0) 9)
    (= (distance machine0 wp0) 9)
    (= (distance wp0 machine1) 20)
    (= (distance machine1 wp0) 20)
    (= (distance wp0 machine2) 17)
    (= (distance machine2 wp0) 17)
    (= (distance wp1 machine0) 20)
    (= (distance machine0 wp1) 20)
    (= (distance wp1 machine1) 13)
    (= (distance machine1 wp1) 13)
    (= (distance wp1 machine2) 16)
    (= (distance machine2 wp1) 16)
    (= (distance wp2 machine0) 13)
    (= (distance machine0 wp2) 13)
    (= (distance wp2 machine1) 18)
    (= (distance machine1 wp2) 18)
    (= (distance wp2 machine2) 21)
    (= (distance machine2 wp2) 21)
    (= (distance wp3 machine0) 15)
    (= (distance machine0 wp3) 15)
    (= (distance wp3 machine1) 18)
    (= (distance machine1 wp3) 18)
    (= (distance wp3 machine2) 15)
    (= (distance machine2 wp3) 15)
    (= (distance wp4 machine0) 12)
    (= (distance machine0 wp4) 12)
    (= (distance wp4 machine1) 19)
    (= (distance machine1 wp4) 19)
    (= (distance wp4 machine2) 20)
    (= (distance machine2 wp4) 20)
    (= (distance machine0 machine1) 28)
    (= (distance machine1 machine0) 28)
    (= (distance machine0 machine2) 25)
    (= (distance machine2 machine0) 25)
    (= (distance machine1 machine2) 4)
    (= (distance machine2 machine1) 4)
)
(:goal (and
    (order_delivered wp3)
    (order_delivered wp0)
    (order_delivered wp2)
))
)
