(define (problem task)
(:domain robot_delivery)
(:objects
wp0 wp1 wp2 wp3 wp4 - waypoint
machine0 machine1 machine2 machine3 - machine
robot0 robot1 robot2 - robot
)
(:init
    (robot_at robot0 wp0)
    (nocarrying_order robot0)
    (undocked robot0)
    (localised robot0)

    (robot_at robot1 wp0)
    (nocarrying_order robot1)
    (undocked robot1)
    (localised robot1)

    (robot_at robot2 wp0)
    (nocarrying_order robot2)
    (undocked robot2)
    (localised robot2)

    (machine_off machine0)
    (machine_off machine1)
    (machine_off machine2)
    (machine_off machine3)

    (delivery_destination wp3)
    (delivery_destination wp4)

    (= (distance wp0 wp1) 19)
    (= (distance wp1 wp0) 19)
    (= (distance wp0 wp2) 7)
    (= (distance wp2 wp0) 7)
    (= (distance wp0 wp3) 12)
    (= (distance wp3 wp0) 12)
    (= (distance wp0 wp4) 19)
    (= (distance wp4 wp0) 19)
    (= (distance wp1 wp2) 13)
    (= (distance wp2 wp1) 13)
    (= (distance wp1 wp3) 14)
    (= (distance wp3 wp1) 14)
    (= (distance wp1 wp4) 25)
    (= (distance wp4 wp1) 25)
    (= (distance wp2 wp3) 14)
    (= (distance wp3 wp2) 14)
    (= (distance wp2 wp4) 25)
    (= (distance wp4 wp2) 25)
    (= (distance wp3 wp4) 12)
    (= (distance wp4 wp3) 12)
    (= (distance wp0 machine0) 24)
    (= (distance machine0 wp0) 24)
    (= (distance wp0 machine1) 13)
    (= (distance machine1 wp0) 13)
    (= (distance wp0 machine2) 19)
    (= (distance machine2 wp0) 19)
    (= (distance wp0 machine3) 16)
    (= (distance machine3 wp0) 16)
    (= (distance wp1 machine0) 18)
    (= (distance machine0 wp1) 18)
    (= (distance wp1 machine1) 19)
    (= (distance machine1 wp1) 19)
    (= (distance wp1 machine2) 11)
    (= (distance machine2 wp1) 11)
    (= (distance wp1 machine3) 4)
    (= (distance machine3 wp1) 4)
    (= (distance wp2 machine0) 18)
    (= (distance machine0 wp2) 18)
    (= (distance wp2 machine1) 19)
    (= (distance machine1 wp2) 19)
    (= (distance wp2 machine2) 13)
    (= (distance machine2 wp2) 13)
    (= (distance wp2 machine3) 10)
    (= (distance machine3 wp2) 10)
    (= (distance wp3 machine0) 13)
    (= (distance machine0 wp3) 13)
    (= (distance wp3 machine1) 6)
    (= (distance machine1 wp3) 6)
    (= (distance wp3 machine2) 8)
    (= (distance machine2 wp3) 8)
    (= (distance wp3 machine3) 17)
    (= (distance machine3 wp3) 17)
    (= (distance wp4 machine0) 8)
    (= (distance machine0 wp4) 8)
    (= (distance wp4 machine1) 9)
    (= (distance machine1 wp4) 9)
    (= (distance wp4 machine2) 15)
    (= (distance machine2 wp4) 15)
    (= (distance wp4 machine3) 28)
    (= (distance machine3 wp4) 28)
    (= (distance machine0 machine1) 16)
    (= (distance machine1 machine0) 16)
    (= (distance machine0 machine2) 8)
    (= (distance machine2 machine0) 8)
    (= (distance machine0 machine3) 21)
    (= (distance machine3 machine0) 21)
    (= (distance machine1 machine2) 11)
    (= (distance machine2 machine1) 11)
    (= (distance machine1 machine3) 22)
    (= (distance machine3 machine1) 22)
    (= (distance machine2 machine3) 14)
    (= (distance machine3 machine2) 14)
)
(:goal (and
    (order_delivered wp3)
    (order_delivered wp4)
))
)
